'use strict';
const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),keys=new Set(),size=2400;
const colors=['#7bffcf','#53bcff','#c9eaff'];
let width,height,started=false,paused=false,ended=false,last=0,time=0,power=0,cooldown=0,dash=0,spawn=0,toastUntil=0;
let player,enemies,shots,particles,seals,camera={x:0,y:0},mouse={x:0,y:0},pointer=false;
const buildings=[];
for(let y=170;y<2200;y+=300)for(let x=170;x<2200;x+=300)buildings.push({x,y,w:170+(x%3)*12,h:180,color:(x+y)%4});
function reset(){player={x:1000,y:1000,hp:100,aura:0,roof:false,kills:0};enemies=[];shots=[];particles=[];seals=[{x:180,y:1000,name:'STORM',active:false},{x:1900,y:400,name:'TIDE',active:false},{x:1900,y:1900,name:'FROST',active:false}];cooldown=0;spawn=0;ended=false;power=0;select(0);}
function resize(){width=innerWidth;height=innerHeight;canvas.width=width*devicePixelRatio;canvas.height=height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
resize();reset();addEventListener('resize',resize);
function toast(t){$('#toast').textContent=t;toastUntil=time+3;}
function select(n){power=n;document.querySelectorAll('[data-power]').forEach(b=>b.classList.toggle('selected',+b.dataset.power===n));}
document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>select(+b.dataset.power));
function pause(){if(!started||ended)return;paused=!paused;$('#pause').textContent=paused?'RESUME · P':'PAUSE · P';}
$('#pause').onclick=pause;
$('#begin').onclick=()=>{reset();started=true;paused=false;$('#overlay').style.display='none';toast('DRAGON SIGNAL DETECTED · FIND THE THREE SEALS');};
addEventListener('keydown',e=>{if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.repeat)return;if('123'.includes(e.key))select(+e.key-1);if(e.key.toLowerCase()==='p')pause();if(e.key.toLowerCase()==='e'&&started&&!paused){const near=buildings.some(b=>player.x>b.x-35&&player.x<b.x+b.w+35&&player.y>b.y-35&&player.y<b.y+b.h+35);if(near||player.roof){player.roof=!player.roof;toast(player.roof?'WALL GRIP · ROOFTOP TRAVERSAL':'RETURNED TO STREET');}}if(e.key.toLowerCase()==='r'&&started&&!paused&&player.aura>=100){player.aura=0;burst(player.x,player.y,'#b497ff',80);enemies.forEach(e=>{if(Math.hypot(e.x-player.x,e.y-player.y)<330)e.hp-=100});toast('DRAGON AURA · UNLEASHED');}});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();pointer=false;if(started&&!paused)pause()});
canvas.addEventListener('mousemove',e=>mouse={x:e.clientX,y:e.clientY});canvas.addEventListener('mousedown',()=>pointer=true);addEventListener('mouseup',()=>pointer=false);
function blocked(x,y){return buildings.some(b=>x>b.x-10&&x<b.x+b.w+10&&y>b.y-10&&y<b.y+b.h+10)}
function burst(x,y,c,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=40+Math.random()*160;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.3+Math.random()*.6,c});}}
function finish(win){ended=true;$('#overlay').style.display='flex';$('.panel small').textContent=win?'ORIGIN CHAPTER COMPLETE':'THE CITY STILL NEEDS YOU';$('h1').innerHTML=win?'THE DRAGON<br><em>AWAKENS.</em>':'RISE AGAIN,<br><em>ULTIMATEMAN.</em>';$('#story').textContent=win?'You restored the three seals and defeated the corrupted sentinels. The dragons have chosen their guardian. This is only the beginning.': 'The sentinels overwhelmed your suit. Use ice to freeze threats, water to heal and push them back, and electricity to finish them. Climb to rooftops to recover your position.';$('#begin').innerHTML='PLAY AGAIN <span>→</span>';}
function update(dt){time+=dt;cooldown-=dt;dash-=dt;spawn-=dt;let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const norm=Math.hypot(dx,dy)||1;let speed=player.roof?245:205;if(keys.has('shift')&&dash<=0&&(dx||dy)){dash=1.5;burst(player.x,player.y,colors[power],15)}if(dash>1.25)speed=640;let nx=Math.max(25,Math.min(size-25,player.x+dx/norm*speed*dt)),ny=Math.max(25,Math.min(size-25,player.y+dy/norm*speed*dt));if(player.roof||!blocked(nx,player.y))player.x=nx;if(player.roof||!blocked(player.x,ny))player.y=ny;
 if((pointer||keys.has(' '))&&cooldown<=0){let a=Math.atan2(mouse.y-height/2,mouse.x-width/2);if(keys.has(' ')&&!pointer){const target=enemies.reduce((best,e)=>!best||Math.hypot(e.x-player.x,e.y-player.y)<Math.hypot(best.x-player.x,best.y-player.y)?e:best,null);if(target)a=Math.atan2(target.y-player.y,target.x-player.x)}shots.push({x:player.x,y:player.y,vx:Math.cos(a)*650,vy:Math.sin(a)*650,life:.8,p:power});cooldown=power===0?.18:.32;burst(player.x,player.y,colors[power],3);}
 if(spawn<=0&&enemies.length<18){const a=Math.random()*Math.PI*2;enemies.push({x:Math.max(20,Math.min(size-20,player.x+Math.cos(a)*550)),y:Math.max(20,Math.min(size-20,player.y+Math.sin(a)*550)),hp:60,freeze:0,hit:0});spawn=1.8;}
 for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const e of enemies){if(s.life>0&&Math.hypot(s.x-e.x,s.y-e.y)<25){e.hp-=s.p===0?32:22;e.hit=.15;if(s.p===2)e.freeze=2.5;if(s.p===1){e.x+=s.vx*.12;e.y+=s.vy*.12;player.hp=Math.min(100,player.hp+3)}burst(e.x,e.y,colors[s.p],12);s.life=0;}}}
 for(const e of enemies){e.freeze-=dt;e.hit-=dt;let d=Math.hypot(player.x-e.x,player.y-e.y);if(e.freeze<=0&&d>0){e.x+=(player.x-e.x)/d*85*dt;e.y+=(player.y-e.y)/d*85*dt}if(d<24&&!player.roof&&e.freeze<=0&&dash<1.25)player.hp-=18*dt;if(e.hp<=0){player.kills++;player.aura=Math.min(100,player.aura+12);burst(e.x,e.y,'#ff7b85',15)}}enemies=enemies.filter(e=>e.hp>0);shots=shots.filter(s=>s.life>0);
 for(const s of seals)if(!s.active&&Math.hypot(player.x-s.x,player.y-s.y)<55){s.active=true;player.hp=Math.min(100,player.hp+30);player.aura=Math.min(100,player.aura+35);burst(s.x,s.y,'#b497ff',60);toast(s.name+' DRAGON SEAL · RESTORED');}
 particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);const count=seals.filter(s=>s.active).length;$('#health').style.width=player.hp+'%';$('#healthText').textContent=Math.ceil(Math.max(0,player.hp));$('#aura').style.width=player.aura+'%';$('#auraText').textContent=player.aura+' / 100';$('#status').textContent=player.roof?'WALL GRIP / ROOFTOP':'STREET LEVEL';$('#progress').textContent=`${count} / 3 seals restored · ${player.kills} / 15 sentinels defeated`;if(count===3)$('#objective').textContent='Clear the remaining sentinels';else $('#objective').textContent='Awaken the three dragon seals';if(player.hp<=0)finish(false);else if(count===3&&player.kills>=15)finish(true);}
function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
function draw(){camera.x=player.x-width/2;camera.y=player.y-height/2;ctx.fillStyle='#080f1c';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(-camera.x,-camera.y);ctx.fillStyle='#101d2b';ctx.fillRect(0,0,size,size);ctx.strokeStyle='#223545';ctx.lineWidth=1;for(let i=0;i<=size;i+=300){ctx.fillStyle='#0a1421';ctx.fillRect(i+55,0,65,size);ctx.fillRect(0,i+55,size,65);ctx.setLineDash([12,20]);ctx.beginPath();ctx.moveTo(i+87,0);ctx.lineTo(i+87,size);ctx.moveTo(0,i+87);ctx.lineTo(size,i+87);ctx.stroke()}ctx.setLineDash([]);
 for(const b of buildings){ctx.fillStyle='#050c1680';ctx.fillRect(b.x+14,b.y+18,b.w,b.h);ctx.fillStyle=['#1b2d40','#1e3443','#243442','#182e3b'][b.color];ctx.fillRect(b.x,b.y,b.w,b.h);ctx.strokeStyle='#426174';ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#132333';ctx.fillRect(b.x+12,b.y+12,b.w-24,b.h-24);for(let y=b.y+22;y<b.y+b.h-12;y+=22)for(let x=b.x+20;x<b.x+b.w-12;x+=24){ctx.fillStyle=(x+y)%5?'#436269':'#6ee6c2';ctx.fillRect(x,y,8,3)}ctx.fillStyle='#294657';ctx.fillRect(b.x+55,b.y+55,35,25);}
 for(const s of seals){const c=s.active?'#7bffcf':'#b497ff';ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(s.x,s.y,35+Math.sin(time*3)*4,0,Math.PI*2);ctx.stroke();circle(s.x,s.y,16,c);ctx.fillStyle=c;ctx.font='10px monospace';ctx.textAlign='center';ctx.fillText(s.name+' SEAL',s.x,s.y-53);}
 for(const e of enemies){circle(e.x,e.y,17,e.freeze>0?'#a3dfff':e.hit>0?'#fff':'#db5d79');circle(e.x,e.y,10,'#292036');ctx.fillStyle='#ffb0b8';ctx.fillRect(e.x-6,e.y-3,12,3);}
 for(const s of shots){ctx.shadowBlur=17;ctx.shadowColor=colors[s.p];circle(s.x,s.y,s.p===0?4:7,colors[s.p]);}ctx.shadowBlur=0;
 for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);circle(p.x,p.y,3,p.c)}ctx.globalAlpha=1;
 ctx.save();ctx.translate(player.x,player.y);if(player.roof){ctx.shadowColor='#7bffcf';ctx.shadowBlur=22;ctx.scale(1.2,1.2)}ctx.rotate(Math.atan2(mouse.y-height/2,mouse.x-width/2)+Math.PI/2);ctx.fillStyle='#02060e';ctx.fillRect(-10,-5,20,28);ctx.strokeStyle=colors[power];ctx.lineWidth=2;ctx.strokeRect(-10,-5,20,28);circle(0,-10,10,'#111b29');ctx.fillStyle=colors[power];ctx.fillRect(-7,-12,14,3);ctx.beginPath();ctx.moveTo(-6,3);ctx.lineTo(0,13);ctx.lineTo(6,3);ctx.stroke();ctx.fillStyle='#121e2c';ctx.fillRect(-17,0,6,15);ctx.fillRect(11,0,6,15);ctx.restore();ctx.restore();
 // Radar shows the entire city and all three objectives.
 const rx=width-162,ry=height-225;ctx.fillStyle='#06121ee8';ctx.fillRect(rx,ry,130,130);ctx.strokeStyle='#3c5c68';ctx.strokeRect(rx,ry,130,130);for(const b of buildings){ctx.fillStyle='#28404e';ctx.fillRect(rx+b.x/size*130,ry+b.y/size*130,b.w/size*130,b.h/size*130)}for(const s of seals)circle(rx+s.x/size*130,ry+s.y/size*130,4,s.active?'#7bffcf':'#b497ff');circle(rx+player.x/size*130,ry+player.y/size*130,3,'#fff');ctx.fillStyle='#91acbd';ctx.font='9px monospace';ctx.fillText('NEON HARBOR',rx+65,ry-8);$('#toast').style.opacity=time<toastUntil?1:0;if(paused){ctx.fillStyle='#060d18b0';ctx.fillRect(0,0,width,height);ctx.fillStyle='#7bffcf';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText('PAUSED',width/2,height/2);}}
function frame(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;if(started&&!paused&&!ended)update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
