import * as THREE from '/vendor/three.module.js';
const $=s=>document.querySelector(s), canvas=$('#world');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true});}catch(e){$('#story').textContent='This 3D game requires WebGL. Enable hardware acceleration in your browser and reload.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setSize(innerWidth,innerHeight);
const scene=new THREE.Scene();scene.background=new THREE.Color('#829db4');scene.fog=new THREE.Fog('#829db4',150,600);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,1000);
scene.add(new THREE.HemisphereLight(0xc3e3ff,0x545042,2));const sun=new THREE.DirectionalLight(0xffddb3,3);sun.position.set(-80,150,80);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-130,right:130,top:130,bottom:-130});scene.add(sun);scene.add(sun.target);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,...extra});
const asphalt=mat('#29333c'),concrete=mat('#a4a9ad'),black=mat('#111823'),green=mat('#53ffc0',{emissive:'#2c9975',emissiveIntensity:1});
function box(w,h,d,m,x,y,z){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);return mesh;}
box(1600,2,1600,mat('#224c67'),0,-3,0);box(760,2,760,asphalt,0,-1,0);
const buildings=[],roofs=[],city=new THREE.Group();scene.add(city);
let seed=7;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const windowGeo=new THREE.BoxGeometry(1.3,1.9,.12), windowMat=mat('#a9c9d5',{metalness:.5,roughness:.25});
const windows=new THREE.InstancedMesh(windowGeo,windowMat,40000);let wi=0;const transform=new THREE.Object3D();
for(let gx=-4;gx<=4;gx++)for(let gz=-4;gz<=4;gz++){
 const x=gx*78,z=gz*78;if(Math.abs(gx)<1&&Math.abs(gz)<1)continue;
 box(60,.7,60,concrete,x,.1,z);
 const h=18+rand()*65+(gz<-1?rand()*35:0),w=42+rand()*7,d=42+rand()*7;
 const b={x,z,w,d,h};buildings.push(b);const color=['#6a6461','#747e88','#8a7164','#536774'][Math.floor(rand()*4)];box(w,h,d,mat(color),x,h/2,z);box(w+1,1.3,d+1,mat('#3a434a'),x,h,z);roofs.push(box(9,3,7,mat('#64727b'),x+8,h+2,z+6));
 for(let y=5;y<h-3;y+=4)for(let side=0;side<4;side++)for(let a=-w/2+4;a<w/2-2;a+=5){transform.position.set(side<2?x+a:x+(side===2?-w/2-.1:w/2+.1),y,side<2?z+(side===0?-d/2-.1:d/2+.1):z+a);transform.rotation.set(0,side<2?0:Math.PI/2,0);transform.updateMatrix();windows.setMatrixAt(wi++,transform.matrix);}
}
windows.count=wi;scene.add(windows);
// Avenue markings, crosswalks, and street furniture.
const paint=mat('#e8d9ab');for(let a=-350;a<360;a+=78){for(let b=-350;b<360;b+=14){box(.3,.03,5,paint,a+39,.03,b);box(5,.03,.3,paint,b,.03,a+39);}for(let b=-312;b<=312;b+=78)for(let j=-3;j<=3;j++){box(1.4,.035,10,concrete,a+39+j*2.3,.05,b+29);}}
for(let i=0;i<60;i++){const x=(Math.floor(rand()*9)-4)*78+32,z=(rand()-.5)*680;box(.35,7,.35,mat('#343e43'),x,3.5,z);box(2,.3,.8,mat('#ffe4a2',{emissive:'#ffd174'}),x+1,7,z);}
const park=box(54,.1,54,mat('#426b48'),0,.1,0);for(let i=0;i<16;i++){let x=(rand()-.5)*50,z=(rand()-.5)*50;box(.7,4,.7,mat('#6c5140'),x,2,z);const tree=new THREE.Mesh(new THREE.IcosahedronGeometry(3.3,1),mat('#315d44'));tree.position.set(x,5,z);scene.add(tree);}
// Original armored hero, built as a articulated silhouette.
const hero=new THREE.Group();scene.add(hero);function part(w,h,d,m,x,y,z){const p=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);p.position.set(x,y,z);p.castShadow=true;hero.add(p);return p;}
part(.85,1.1,.45,black,0,1.55,0);part(.64,.65,.6,black,0,2.43,0);part(.5,.1,.04,green,0,2.46,-.32);part(.12,.8,.48,green,0,1.58,0);const legs=[part(.3,.85,.32,black,-.23,.55,0),part(.3,.85,.32,black,.23,.55,0)];const arms=[part(.26,1,.3,black,-.61,1.55,0),part(.26,1,.3,black,.61,1.55,0)];part(.3,.15,.34,green,-.61,1.2,0);part(.3,.15,.34,green,.61,1.2,0);
const auraRing=new THREE.Mesh(new THREE.TorusGeometry(2,.07,8,40),green);auraRing.rotation.x=Math.PI/2;auraRing.position.y=.1;hero.add(auraRing);auraRing.visible=false;
let state,active=false,paused=false,ended=false,yaw=0,pitch=.22,power=0,cool=0,spawn=0,clock=0;const keys=new Set(),enemies=[],shots=[],effects=[],seals=[];const palette=[0x65ffbd,0x4ab9ff,0xd6f2ff];
for(const [x,z,name] of [[-234,78,'STORM'],[234,-156,'TIDE'],[156,234,'FROST']]){const group=new THREE.Group();group.position.set(x,buildings.find(b=>b.x===x&&b.z===z).h+2,z);const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(2.4),mat('#ae8aff',{emissive:'#9365ff',emissiveIntensity:2}));group.add(crystal);const ring=new THREE.Mesh(new THREE.TorusGeometry(4,.15,8,40),mat('#b893ff',{emissive:'#9365ff'}));ring.rotation.x=Math.PI/2;group.add(ring);scene.add(group);seals.push({group,crystal,name,active:false});}
function reset(){for(const e of [...enemies,...shots,...effects])scene.remove(e.mesh);enemies.length=shots.length=effects.length=0;seals.forEach(s=>{s.active=false;s.crystal.material.color.set('#ae8aff')});state={pos:new THREE.Vector3(39,0,39),vy:0,hp:100,aura:0,kills:0,climb:false,dash:0};cool=spawn=0;ended=false;hero.position.copy(state.pos);select(0);}
function select(n){power=n;green.color.setHex(palette[n]);green.emissive.setHex(palette[n]);document.querySelectorAll('[data-power]').forEach(b=>b.classList.toggle('selected',+b.dataset.power===n));}
function toast(t){$('#toast').textContent=t;$('#toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.opacity=0,3000);}
function pause(){if(!active||ended)return;paused=!paused;$('#pause').textContent=paused?'RESUME · P':'PAUSE · P';if(paused)document.exitPointerLock?.();}
$('#pause').onclick=pause;document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>select(+b.dataset.power));
$('#begin').onclick=()=>{reset();active=true;paused=false;$('#overlay').style.display='none';canvas.requestPointerLock?.();toast('FIND THE ROOFTOP DRAGON SEALS · E TO CLIMB');};
let firing=false;canvas.onmousedown=()=>{if(!active||paused)return;canvas.requestPointerLock?.();firing=true};addEventListener('mouseup',()=>firing=false);addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){yaw-=e.movementX*.0025;pitch=Math.max(-.35,Math.min(1.05,pitch+e.movementY*.002));}});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if('123'.includes(k))select(+k-1);if(k==='p')pause();if(!active||paused||ended)return;if(k==='e')state.climb=!state.climb;if(k===' '&&state.pos.y<=floorAt(state.pos)+.1)state.vy=12;if(k==='r'&&state.aura>=100){state.aura=0;for(const enemy of enemies)if(enemy.mesh.position.distanceTo(state.pos)<40)enemy.hp-=120;effect(state.pos,0xb58cff,10);toast('DRAGON AURA UNLEASHED');}});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();firing=false;if(active&&!paused&&!ended)pause()});
function inside(b,p,pad=0){return Math.abs(p.x-b.x)<b.w/2+pad&&Math.abs(p.z-b.z)<b.d/2+pad;}
function floorAt(p){let h=0;for(const b of buildings)if(inside(b,p)&&p.y>=b.h-.5)h=Math.max(h,b.h+.7);return h;}
function effect(pos,color,r=1){const mesh=new THREE.Mesh(new THREE.SphereGeometry(r,8,6),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7,wireframe:true}));mesh.position.copy(pos);scene.add(mesh);effects.push({mesh,life:.5});}
function finish(win){ended=true;firing=false;document.exitPointerLock?.();$('#overlay').style.display='flex';$('.panel small').textContent=win?'ORIGIN CHAPTER COMPLETE':'THE CITY NEEDS ITS GUARDIAN';$('h1').innerHTML=win?'THE DRAGON<br><em>AWAKENS.</em>':'RISE AGAIN,<br><em>ULTIMATEMAN.</em>';$('#story').textContent=win?'The three rooftop seals are restored. The sentinels have fallen. Ultimateman is the new guardian of Neon Manhattan.':'Use water to heal, ice to freeze enemies, and wall climbing to reach safety. Restore the rooftop seals to recover health.';$('#begin').innerHTML='PLAY AGAIN <span>→</span>';}
function update(dt){clock+=dt;cool-=dt;spawn-=dt;state.dash-=dt;const forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));let move=forward.clone().multiplyScalar((keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0)).addScaledVector(right,(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0));if(move.length()>0)move.normalize();let speed=keys.has('shift')?25:13;const next=state.pos.clone().addScaledVector(move,speed*dt);let wall=buildings.find(b=>inside(b,next,1)&&state.pos.y<b.h);if(wall){if(state.climb&&move.length()>0){state.pos.y+=20*dt;state.vy=0;$('#status').textContent='WALL GRIP · ASCENDING';if(state.pos.y>=wall.h){state.pos.y=wall.h+1;state.pos.copy(next.setY(state.pos.y));}}}else{state.pos.x=THREE.MathUtils.clamp(next.x,-365,365);state.pos.z=THREE.MathUtils.clamp(next.z,-365,365);}
 if(!wall||!state.climb||move.length()===0){state.vy-=30*dt;state.pos.y+=state.vy*dt;const floor=floorAt(state.pos);if(state.pos.y<=floor){state.pos.y=floor;state.vy=0;}$('#status').textContent=state.pos.y>5?'ROOFTOP / AIRBORNE':'STREET LEVEL';}
 hero.position.copy(state.pos);if(move.length()>0)hero.rotation.y=Math.atan2(-move.x,-move.z);legs[0].rotation.x=Math.sin(clock*12)*(move.length()>.1?.5:0);legs[1].rotation.x=-legs[0].rotation.x;arms[0].rotation.x=-legs[0].rotation.x;arms[1].rotation.x=legs[0].rotation.x;auraRing.visible=state.aura>=100;
 if((firing||keys.has('f'))&&cool<=0){const origin=state.pos.clone().add(new THREE.Vector3(0,1.7,0));let target=enemies.filter(e=>e.mesh.position.distanceTo(origin)<95).sort((a,b)=>a.mesh.position.distanceTo(origin)-b.mesh.position.distanceTo(origin))[0];let direction=target?target.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(origin).normalize():forward.clone();const mesh=new THREE.Mesh(new THREE.SphereGeometry(power===0?.2:.4,8,8),new THREE.MeshBasicMaterial({color:palette[power]}));mesh.position.copy(origin);scene.add(mesh);shots.push({mesh,dir:direction,life:1.5,p:power});cool=power===0?.2:.4;}
 if(spawn<=0&&enemies.length<14){let p=state.pos.clone();p.x+=(rand()-.5)*90;p.z+=(rand()-.5)*90;p.y=floorAt(p);if(!buildings.some(b=>inside(b,p)&&p.y<b.h)){const mesh=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(1.2,2,1),mat('#813e53',{emissive:'#421624'}));body.position.y=1;mesh.add(body);const eye=new THREE.Mesh(new THREE.BoxGeometry(.8,.15,1.1),mat('#ff9b88',{emissive:'#ff5544'}));eye.position.y=1.6;mesh.add(eye);mesh.position.copy(p);scene.add(mesh);enemies.push({mesh,hp:60,freeze:0});}spawn=1.3;}
 for(const s of shots){s.life-=dt;s.mesh.position.addScaledVector(s.dir,65*dt);for(const e of enemies)if(s.life>0&&e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).distanceTo(s.mesh.position)<1.5){e.hp-=s.p===0?32:24;if(s.p===2)e.freeze=3;if(s.p===1){state.hp=Math.min(100,state.hp+4);e.mesh.position.addScaledVector(s.dir,4);}effect(s.mesh.position,palette[s.p]);s.life=0;}}
 for(const e of enemies){e.freeze-=dt;const d=e.mesh.position.distanceTo(state.pos);if(e.freeze<=0&&d>1.8){const step=state.pos.clone().sub(e.mesh.position);step.y=0;step.normalize().multiplyScalar(dt*5);const p=e.mesh.position.clone().add(step);if(!buildings.some(b=>inside(b,p)&&p.y<b.h))e.mesh.position.copy(p);}if(d<2.4&&e.freeze<=0)state.hp-=15*dt;if(e.hp<=0){state.kills++;state.aura=Math.min(100,state.aura+12);effect(e.mesh.position,0xff6688,2);}}
 for(let i=enemies.length-1;i>=0;i--)if(enemies[i].hp<=0){scene.remove(enemies[i].mesh);enemies.splice(i,1)}for(let i=shots.length-1;i>=0;i--)if(shots[i].life<=0){scene.remove(shots[i].mesh);shots[i].mesh.geometry.dispose();shots[i].mesh.material.dispose();shots.splice(i,1)}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.mesh.scale.multiplyScalar(1+dt*3);e.mesh.material.opacity=Math.max(0,e.life);if(e.life<=0){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1)}}
 for(const s of seals){s.crystal.rotation.y+=dt;s.crystal.position.y=Math.sin(clock*2);if(!s.active&&s.group.position.distanceTo(state.pos)<6){s.active=true;s.crystal.material.color.set('#65ffbd');state.hp=Math.min(100,state.hp+35);state.aura=Math.min(100,state.aura+35);toast(s.name+' SEAL RESTORED');}}
 const n=seals.filter(s=>s.active).length;$('#health').style.width=state.hp+'%';$('#healthText').textContent=Math.ceil(Math.max(0,state.hp));$('#aura').style.width=state.aura+'%';$('#auraText').textContent=state.aura+' / 100';$('#progress').textContent=`${n} / 3 rooftop seals · ${state.kills} / 15 sentinels`;if(state.hp<=0)finish(false);else if(n===3&&state.kills>=15)finish(true);
 const nearest=seals.filter(s=>!s.active).sort((a,b)=>a.group.position.distanceTo(state.pos)-b.group.position.distanceTo(state.pos))[0];$('#objective').textContent=nearest?`${nearest.name} seal · ${Math.round(nearest.group.position.distanceTo(state.pos))} m`:'Defeat the remaining sentinels';
}
const radar=document.createElement('canvas');radar.width=160;radar.height=160;radar.style.cssText='position:absolute;right:32px;bottom:140px;width:160px;height:160px;border:1px solid #456474;background:#0b1728';document.body.append(radar);const rc=radar.getContext('2d');function drawRadar(){rc.clearRect(0,0,160,160);rc.fillStyle='#375264';for(const b of buildings)rc.fillRect((b.x+380)/760*160-b.w/760*80,(b.z+380)/760*160-b.d/760*80,b.w/760*160,b.d/760*160);for(const s of seals){rc.fillStyle=s.active?'#65ffbd':'#bc8aff';rc.beginPath();rc.arc((s.group.position.x+380)/760*160,(s.group.position.z+380)/760*160,4,0,7);rc.fill()}rc.fillStyle='white';rc.beginPath();rc.arc((state.pos.x+380)/760*160,(state.pos.z+380)/760*160,3,0,7);rc.fill();}
reset();let last=performance.now();function frame(t){const dt=Math.min((t-last)/1000,.04);last=t;if(active&&!paused&&!ended)update(dt);const target=state.pos.clone().add(new THREE.Vector3(0,2,0));const offset=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch)*10,4+Math.sin(pitch)*10,Math.cos(yaw)*Math.cos(pitch)*10);camera.position.lerp(target.clone().add(offset),1-Math.exp(-dt*12));camera.lookAt(target);sun.position.copy(state.pos).add(new THREE.Vector3(-80,150,80));sun.target.position.copy(state.pos);drawRadar();renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
